[build]
  publish = "."
  functions = "netlify/functions"

# Redirect /admin to the admin interface
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# Add header for Netlify Identity
[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

# Add headers for the admin path to ensure the CMS loads correctly
[[headers]]
  for = "/admin/*"
    [headers.values]
    Content-Type = "text/html"
    Cache-Control = "public, max-age=0, must-revalidate"
